### ISSUE TITLE
ENH: Add power operator to mathinterpreter, example '2^2 == 4'

### ISSUE THREAD

**Issue by aureliobarbosa** [ScientificThought/py-math-interpreter#23]
Before adding this operation, write the test.

**Comment by aureliobarbosa** [comment]
@hsguidi 

Here is how to use mark a test to be skip by pytest. 

https://docs.pytest.org/en/8.0.x/how-to/skipping.html

**Comment by hsguidi** [comment]
@aureliobarbosa 
To implement multi char symbols, like '**', 'sin', 'ln'..., we need remake 'lexer.py'.
This is something I would like to do, but I am not sure if now is the best moment.

**Comment by aureliobarbosa** [comment]
Understood. As an exercise you implement the rest of division operator, '%'. What do you think?

**Comment by aureliobarbosa** [comment]
This is being tracked on #30.
