### ISSUE TITLE
ENH: A few modules to consider in order to improve CLI

### ISSUE THREAD

**Issue by hsguidi** [ScientificThought/py-math-interpreter#25]
https://docs.python.org/3/library/code.html

https://python-prompt-toolkit.readthedocs.io/en/master/pages/gallery.html
https://github.com/bchao1/bullet
https://github.com/Textualize/textual
https://github.com/bczsalba/pytermgui

**Comment by aureliobarbosa** [comment]
I think the usage for [bullet](https://github.com/bchao1/bullet) is different for the current goal, which is a REPL. Maybe it could be useful for making a standard calculator with a terminal interface? 

After including a useful CLI we could think about it, but this project is starting as a playground and I would like not to get too much ambitious.

**Comment by aureliobarbosa** [comment]
@hsguidi I really enjoyed Textualize... I we jump into making a terminal interface for the calculator, we could try to adapt the calculator they use and apply the engine of this project to their calculator... It seems like a nice project to show case developing a library and CLI interface. 

It could actually be a 'math-calculator' project importing this library. And we could stick with this library as being just a library, maybe complementing it with simple operations which are missing.

**Comment by aureliobarbosa** [comment]
The person who created [pytermigui](https://github.com/bczsalba/pytermgui) is trying to create an organization named Shade 40, with a modern terminal app. I am not sure whether it is there yet. And it seems much more complex. You need to write the app using a XML standard.
