### ISSUE TITLE
ENH: Implement a function to 'calculate' an expression

### ISSUE THREAD

**Issue by hsguidi** [ScientificThought/py-math-interpreter#29]
Seems to me that is unnecessary to expose the process
input -> lexer -> tokens -> parser -> tree -> interpreter -> output 
to user.
The library should have a default evaluation function.

**Comment by aureliobarbosa** [comment]
Nice idea. The library can expose it through lib.lexer, but it would be useful to have a simple function.

evaluate?

solve?

calc?

**Comment by aureliobarbosa** [comment]
calculate

**Comment by aureliobarbosa** [comment]
@hsguidi, I assign it to you, as discussed on #30 .
