### ISSUE TITLE
Create .deb package

### ISSUE THREAD

**Issue by aureliobarbosa** [ScientificThought/py-math-interpreter#43]
Official Guide can be found here (143 pages...)

https://www.debian.org/doc/manuals/debmake-doc/debmake-doc.en.pdf
https://www.debian.org/doc/manuals/debmake-doc/

A more pragmatic approach:

https://wiki.debian.org/HowToPackageForDebian

**Comment by aureliobarbosa** [comment]
More info on "Introduction to debian packaging"

https://wiki.debian.org/Packaging/Intro?action=show&redirect=IntroDebianPackaging

**Comment by aureliobarbosa** [comment]
This is the place to start:

https://www.debian.org/doc/devel-manuals#packaging-tutorial

**Comment by aureliobarbosa** [comment]
https://medium.com/@flavienb/packaging-software-for-debian-systems-19562b077050

**Comment by hsguidi** [comment]
After @aureliobarbosa  created a snap installable, create a .deb seems unnecessary.
 Lets abandon this idea for now.
