### ISSUE TITLE
mathinterpreter breaking on Ctrl-C, instead of nicely finishing

### ISSUE THREAD

**Issue by aureliobarbosa** [ScientificThought/py-math-interpreter#49]
This is the output of the REPL when the user types Ctrl-C
```bash
❯ mathinterpreter
calc > ^CTraceback (most recent call last):
  File "/home/aureliobarbosa/mycode/math/env/bin/mathinterpreter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aureliobarbosa/mycode/math/mathinterpreter/__main__.py", line 6, in main
    text = input("calc > ").strip()
           ^^^^^^^^^^^^^^^^
KeyboardInterrupt
❯ 
```

I expected the REPL could capture this.

**Comment by hsguidi** [comment]
This demand is part of issue #25.
I am closing this issue.

**Comment by aureliobarbosa** [comment]
thanks.

**Comment by aureliobarbosa** [comment]
Even after improving the terminal (on branch `readline`, not merged yet), this problem continues.
So I am bringing back this issue.

![image](https://github.com/ScientificThought/py-math-interpreter/assets/15037098/5a61405b-5dd9-4a7e-a030-e257d3bd4741)
