### ISSUE TITLE
Implement rest of division operator, using character '%' as in Python.

### ISSUE THREAD

**Issue by aureliobarbosa** [ScientificThought/py-math-interpreter#50]
Note that modulo operator '%' in python also float numbers.

Below I copy-past some code:
```python 
❯ python
Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 3//2
1
>>> 3%2
1
>>> 3%1
0
>>> 3.2%1
0.20000000000000018
>>> 3.2//1
3.0
>>> 5%2
1
>>> 5.1%2
1.0999999999999996
>>> 5.2%2
1.2000000000000002
>>> 4%2.2
1.7999999999999998
```
@hsguidi I think we are just free to implement this too.

**Comment by aureliobarbosa** [comment]
> Note that modulo operator '%' in python also float numbers.
> 
> Below I copy-past some code:
> 
> ```python
> ❯ python
> Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> 3//2
> 1
> >>> 3%2
> 1
> >>> 3%1
> 0
> >>> 3.2%1
> 0.20000000000000018
> >>> 3.2//1
> 3.0
> >>> 5%2
> 1
> >>> 5.1%2
> 1.0999999999999996
> >>> 5.2%2
> 1.2000000000000002
> >>> 4%2.2
> 1.7999999999999998
> ```
> 
> @hsguidi I think we are just free to implement this too.

**Comment by hsguidi** [comment]
> > Note that modulo operator '%' in python also float numbers.
> > Below I copy-past some code:
> > ```python
> > ❯ python
> > Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux
> > Type "help", "copyright", "credits" or "license" for more information.
> > >>> 3//2
> > 1
> > >>> 3%2
> > 1
> > >>> 3%1
> > 0
> > >>> 3.2%1
> > 0.20000000000000018
> > >>> 3.2//1
> > 3.0
> > >>> 5%2
> > 1
> > >>> 5.1%2
> > 1.0999999999999996
> > >>> 5.2%2
> > 1.2000000000000002
> > >>> 4%2.2
> > 1.7999999999999998
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @hsguidi I think we are just free to implement this too.

You convinced me.
